name: 离线下载

on:
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          git clone https://SakuraKyuo:${{ secrets.MYTOKEN }}@github.com/SakuraKyuo/android_kernel_xiaomi_sdm710-twilight kernel 
           git config --global user.email "sakurakyuo@protonmail.com"
           git config --global user.name "sakurakyuo"

      - name: remote
        run: |
          cd kernel
          wget https://github.com/SakuraKyuo/android_kernel_xiaomi_sdm710-twilight/commit/11780c3f30c00c173f1b784c71373c03f029ef35.patch && git am 11780c3f30c00c173f1b784c71373c03f029ef35.patch
          wget https://github.com/SakuraKyuo/android_kernel_xiaomi_sdm710-twilight/commit/8290394e8e178e27e6e7acdaf1e21f3dce62540e.patch && git am 8290394e8e178e27e6e7acdaf1e21f3dce62540e.patch
          git revert 2ed2755
          wget https://github.com/SakuraKyuo/android_kernel_xiaomi_sdm710-twilight/commit/9e6d88cb77492c131d05b221de01621e5e7b3d92.patch && git am 9e6d88cb77492c131d05b221de01621e5e7b3d92.patch
          git revert d7411ac
      - name: pick push
        run: |
          cd kernel 
          git push
