name: 离线下载

on:
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          git clone https://github.com/ShivamKumarJha/android_tools
           git clone https://dumps.tadiphone.dev/dumps/oneplus/op5961l1 -b qssi-user-13-TP1A.220905.001-1690190202851-release-keys--IN --depth=1

      - name: remote
        run: |
          cd android_tools
          chmod +x setup.sh
          sudo bash setup.sh
          bash tools/proprietary-files.sh op5961l1
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: android_tools/working/proprietary-files.txt
