name: 离线下载

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'GitLab Link'
        required: true
      branch:
        description: 'branch'
        required: true
      repourl:
        description: 'repourl'
        required: true
      repobranch:
        description: 'repobranch'
        required: true

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          cd ~
          git clone ${{ github.event.inputs.url }} -b ${{ github.event.inputs.branch }} output

      - name: Import Origin
        run: |
          cd ~/output
          git remote set-url origin https://SakuraKyuo:${{ secrets.MYTOKEN }}@github.com/${{ github.event.inputs.repourl }}

      - name: Create branch
        run: |
          cd ~/output
          git switch -c ${{ github.event.inputs.repobranch }}

      - name: Push
        run: |
          cd ~/output
          git push -u origin ${{ github.event.inputs.repobranch }}
