name: 离线下载

on:
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          git clone https://SakuraKyuo:${{ secrets.MYTOKEN }}@github.com/SakuraKyuo/android_kernel_xiaomi_sdm710 -b UDC kernel 
           git config --global user.email "sakurakyuo@protonmail.com"
           git config --global user.name "sakurakyuo"

      - name: remote
        run: |
          cd kernel
          wget https://github.com/B--B/android_kernel_xiaomi_sdm710/commit/c73e023de0a4b4c6ec040f3c44595b5e66af8751.patch
          git am c73e023de0a4b4c6ec040f3c44595b5e66af8751.patch
      - name: pick push
        run: |
          cd kernel 
          git push
