name: 离线下载

on:
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          git clone https://SakuraKyuo:${{ secrets.MYTOKEN }}@github.com/SakuraKyuo/android_kernel_xiaomi_sdm710_bpf -b lineage-18.1 kernel 
           git config --global user.email "sakurakyuo@protonmail.com"
           git config --global user.name "sakurakyuo"

      - name: remote
        run: |
          cd kernel
          git reset --hard HEAD~9
      - name: pick push
        run: |
          cd kernel 
          git push -f
