name: 离线下载

on:
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        run: |
          git clone https://SakuraKyuo:${{ secrets.MYTOKEN }}@github.com/SakuraKyuo/frameworks_base 

      - name: remote
        run: |
          cd frameworks_base
          git remote add apn https://github.com/VoltageOS-staging/frameworks_base
          git fetch apn

      - name: pick push
        run: |
          cd frameworks_base
          git cherry-pick e772135^..ec05f56
          git push
